# Pipefish Husbandry Protocols

\newpage

## Pipefish Feeding

(created by M Currey 7/23/09)

**Materials Needed:** 

- Decapsualted Brine Shrimp (see artemia decapsulations SOP)
- Adult Brine Shrimp
- Live Moina
- Frozen myisid Shrimp
- Live mysid shrimp
- Shrimp collector
- Squirt Bottle
- 
### Fish foods for fry, juvenile and adults:

- Fry - newly hatched baby brine shrimp (see hatching brine shrimp SOP), salt water copepods. Fry are fed once per day
- Adult – newly hatched brine shrimp, Adult brine shrimp, Moina. Adults are fed once per day. Feed adult brine shrimp when we have them. Use moina when we are out of adult brine shrimp. Adult brine shrimp are from a local fish store and are only available every tow weeks. They last ~ one week and therefore adult pipefish are fed adult brine shrimp for one week and moina the next. 

**Fry:**

         Fry tanks are designated with an orange dot. 

1. Newly hatched brine: Collect newly hatched brine and place into a squirt bottle (see brine shrimp SOP). Feed all tanks with an orange dot. 

**Adults:**

        Adult tanks are designated with a yellow dot. 

1. Newly hatched brine: Collect newly hatched brine and place into a squirt bottle (see brine shrimp SOP). Feed all tanks with an orange dot. 
1. Frozen Mysis: Obtain a quarter-sized piece of frozen mysis from the freezer. Place into squirt bottle and add water. Wait until mysis thaws and feed to all adult tanks. 
1. Adult Brine shrimp: Scoop out adult brine shrimp with net. Wash into a ball and place over the top of squirt bottle. Wash ball of brine into squirt bottle and feed all adult pipefish. 
1. Moina: Scoop out with net and wash into a ball. Invert ball over collection beaker and wash moina into beaker. Pour moina into squirt bottle and feed. 
1. Live Mysid: See live foods SOP

## **Live Food Culture, Monia and Mysid Shrimp:** 

**_Moina_**

**Materials:** 

- 10 gallon glass tanks
- corner sponge filter
- Air supply
- Rotifer diet
- Powdered nannochloropsis 

**Procedure:** 

- Fill 10 gallon tank 3/4 full of stickleback system water
- Add corner filter and activate with air. 
- Add Moina
- Change water once every 2-3 weeks by removing half of the water and replacing with stickleback water. 
- DO NOT break tank down and clean as moina do not respond well to this. 

**Feeding:** 

- Add 15 drops of rotifer diet and 1/8 scoop of powdered nannochloropsis each day. 

###### Collection and feeding to fish

- See pipefish feeding SOP

###### _Mysid Shrimp_

For a description of the mysid generator please visit: 

http://www.mblaquaculture.com/assets/docs/MBL_AQ_Mysid_Generator.pdf

**Materials:** 

- 10 gallon tank generator system
- Salt water

**Feeding:**

- Feed newly hatched brine shrimp daily to both adults and juveniles. 

**Water Change:**

- 2-3 times per week empty 5 gallons of water from the system and replace with new make up water. 
- Make new water in 5 gallon bucket by adding DI water and 2 scoops of salt. 

**Juvenile Collection (Daily):**  

- Turn off water to tanks. 
- Remove collection cup, using mysid system water, rinse juveniles into plastic container. 
- Pour juveniles into grow out tank.
- Replace collection cup. 
- Turn water on and start siphon. 

**Adults collection and feeding to pipefish:** 

Juvenile will reach adult size in three weeks. At three weeks these new adults will replace old breeding adults. The old breeding adults that are being replaced are feed to the pipefish. 

- Let juveniles grow to three weeks at which point they reach adult stage
- Siphon adults through a net and collect in a container. 
- Siphon old adults out of one of the 10 gallon tanks and feed to pipefish
- Clean tank, fill with water and add new adult. 

\newpage

## Live Food Culture, Monia and Mysid Shrimp: 

**_Moina_**

**Materials:** 

- 10 gallon glass tanks
- corner sponge filter
- Air supply
- Rotifer diet
- Powdered nannochloropsis 

**Procedure:** 

- Fill 10 gallon tank 3/4 full of stickleback system water
- Add corner filter and activate with air. 
- Add Moina
- Change water once every 2-3 weeks by removing half of the water and replacing with stickleback water. 
- DO NOT break tank down and clean as moina do not respond well to this. 

**Feeding:** 

- Add 15 drops of rotifer diet and 1/8 scoop of powdered nannochloropsis each day. 

###### Collection and feeding to fish

- See pipefish feeding SOP

###### _Mysid Shrimp_

For a description of the mysid generator please visit: 

http://www.mblaquaculture.com/assets/docs/MBL_AQ_Mysid_Generator.pdf

**Materials:** 

- 10 gallon tank generator system
- Salt water

**Feeding:**

- Feed newly hatched brine shrimp daily to both adults and juveniles. 

**Water Change:**

- 2-3 times per week empty 5 gallons of water from the system and replace with new make up water. 
- Make new water in 5 gallon bucket by adding DI water and 2 scoops of salt. 

**Juvenile Collection (Daily):**  

- Turn off water to tanks. 
- Remove collection cup, using mysid system water, rinse juveniles into plastic container. 
- Pour juveniles into grow out tank.
- Replace collection cup. 
- Turn water on and start siphon. 

**Adults collection and feeding to pipefish:** 

Juvenile will reach adult size in three weeks. At three weeks these new adults will replace old breeding adults. The old breeding adults that are being replaced are feed to the pipefish. 

- Let juveniles grow to three weeks at which point they reach adult stage
- Siphon adults through a net and collect in a container. 
- Siphon old adults out of one of the 10 gallon tanks and feed to pipefish
- Clean tank, fill with water and add new adult. 



