--- 
title: "Cresko Laboratory Manual"
author: "Cresko Lab"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is the Cresko Laboratory Manual"
---

# The Cresko Lab

Description of our laboratory

<!--chapter:end:index.Rmd-->

# Introduction to the Lab

Description of our lab ....

<!--chapter:end:01-intro.Rmd-->

# Mission and Vision

We describe our methods in this chapter.

<!--chapter:end:02-mission_vision.Rmd-->

# Expectations in the Laboratory

We describe our methods in this chapter.

<!--chapter:end:03-expectations.Rmd-->

# IACUC

descriptions of animal care IACUC protocols


<!--chapter:end:04-IACUC.Rmd-->

# Histological Protocols

## Alizarin Staining

### PURPOSE: Alizarin staining of fixed adult stickleback.

### MATERIALS:

- 0.5% Alizarin red S Stock: To make 50 mls add 0.25g alizarin red S powder to 50 ml water.
- 0.025% Alizarin Stain: To make 100 mls: Add 500µl 0.5% alizarin red S (stock) to 99.5ml 1% KOH
- 1 Liter: Add 5ml 0.5% alizarin red S (stock) to 9950ml (1 liter) 1%KOH
- 3% H202/0.5%KOH: Mix and keep at 4C; Before using, bring to room temperature to hold down
- introducing bubbles under the skin: 0.5ml 6%H202 & 0.5ml 1%KOH.
- MESAB: Tricaine: 3-amino benzoic acid ethyl ester from Sigma (Cat \# A-5040). Mix in fish safe container with a stir bar:
	-   400 mg tricaine powder
	-   800 mg Na2HPO4 (anhydrous)
	-   100 ml glass distilled water

Adjust to \~pH 7 with a drop at a time of 1N NaOH or 1N HCl if needed
but it's usually right if you weigh the sodium phosphate carefully and
measure the water with a graduated cylinder.

For storage: Aliquot into 6 x 25 ml fish safe plastic bottles and store
at 4C. Label with date made and use within a couple of weeks.

8% PFA: {#pfa .subhead2}

-   8 g Pelleted PFA (Ted Pella, Inc.; cat\# 18501)
-   90 ml dH2O
-   25 drops 1N NaOH

1.  Heat at very low heat and stir until solution clears.
2.  Add 25 drops 1N HCl. pH should be 7.0-7.2.
3.  Filter and store at 4C not more than 1 week.
4.  Use as 4% PFA: dilute 1:1 with 2X PBS, do not store solution more
    than a few hours.

2X PBS {#x-pbs .subhead2}

-   1.6% NaCl
-   0.04% KCl
-   0.04 M PO4 pH 7.0- 7.3


### Procedure:


Day

Step

Time for Step

Date and Time

1

2h-8h at R/T depending on size on shaker.

1h or longer at R/T on shaker.

Without agitation and with lid open until eyes start to lighten and all
skin pigment is gone (usually about an hour or more)


2

2 h to O/N at R/T on shaker


2 h to overnight O/N at R/T on shaker.\
Check for bone staining.


R/T on shaker until excess stain in tissue is gone.


Without agitation

Wild caught specimens are put in 100% EtOH in the field and then
rehydrated and put into 4% when back in the lab.

<!--chapter:end:05-protocols.Rmd-->

`r if (knitr:::is_html_output()) '
# References {-}
'`

<!--chapter:end:06-references.Rmd-->

